/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NPopover: typeof import('naive-ui')['NPopover']
  const NTag: typeof import('naive-ui')['NTag']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}